apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace

  tasks:
    - name: npminstall
      taskRef:
        name: npminstall
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: tests
      runAfter:
        - npminstall
      taskRef:
        name: tests
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build
      runAfter:
        - tests
      taskRef:
        name: build
      workspaces:
        - name: source
          workspace: shared-workspace
